
- hosts: Device
  tasks:
    - name: remove latest data
      file:
        path: /tmp/unzip_output.log
        state: absent

    - name: run unzip
      shell: "cd /tmp/scripts && ./untar.sh"
      register: logdata
      ignore_errors: yes

    - lineinfile: create=yes  dest=/tmp/unzip_output.log line="{{ logdata.stdout+logdata.stderr }}" state=present


    - name: fetch result
      fetch:
        src: /tmp/unzip_output.log
        dest: /tmp/unzip_output.log
        flat: yes
